### ISSUE TITLE
Add color scale option 'custom'

### ISSUE THREAD

**Issue by lenafm** [datasketch/app-maps-leaflet#15]
Add option 'custom' in the color scale drop down. When 'custom' is selected the user is promted to enter the custoff points that will be used for the color scale.

**Comment by CamilaAchuri** [comment]
in this moment the options are
![image](https://user-images.githubusercontent.com/17035597/125516103-c649cfcb-a7b0-4016-a71d-f56abcced23a.png)
"custom" option renamed "categorical"
