### ISSUE TITLE
Review maps by municipalities

### ISSUE THREAD

**Issue by JulianaGalvisN** [datasketch/app-maps-leaflet#17]
Estaba intentando usar esta app https://datasketch.shinyapps.io/app-maps-leaflet/?map_name=mex_municipalities pero me sale anuncio de error cuando intento editar los datos de cada municipio, igual me pasó con https://datasketch.shinyapps.io/app-maps-leaflet/?map_name=gtm_municipalities

**Comment by CamilaAchuri** [comment]
Juli, los estabas editando desde la tabla o estabas ingresando alguna base?

**Comment by JulianaGalvisN** [comment]
Las dos. Traté de modificar la base que ya está, pero también intenté con copiar y pegar los datos que hay en esta base de datos (hoja 2) https://docs.google.com/spreadsheets/d/1Ro5sLWe6Dz-8Xqhj2BNlyyWTqKXkPBjyPBNXB636GBI/edit?usp=sharing
